In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('D:\DATA SCIENCE Internship with Innomatics\Data Analysis\laptop_price.csv')
df.head()

Brand         Processor Type Operating System RAM Type RAM Size Disc Type  \
0  Lenovo          Intel Core i3       Windows 11     DDR4      8GB       SSD   
1  Lenovo          Intel Core i3       Windows 11     DDR4      8GB       SSD   
2    ASUS          Intel Core i3       Windows 11     DDR4      8GB       SSD   
3      HP  AMD Ryzen 5 Hexa Core       Windows 10     DDR4      8GB       SSD   
4    ASUS          Intel Core i5       Windows 11     DDR4      8GB       SSD   

  Disc Size    MRP  
0     256GB  36990  
1     512GB  39990  
2     512GB  32990  
3     512GB  49990  
4     512GB  49990

In [3]:
data=df.copy()

### Convert categorical columns to numeric column

#### BRAND

In [4]:
data['Brand'].unique()

array(['Lenovo', 'ASUS', 'HP', 'DELL', 'RedmiBook', 'realme', 'acer',
       'MSI', 'APPLE', 'Infinix', 'SAMSUNG', 'Ultimus', 'Vaio',
       'GIGABYTE', 'Nokia', 'ALIENWARE'], dtype=object)

In [5]:
def replace_brand(brand):
    if brand=='Lenovo':
        return 1
    elif brand=='ASUS':
        return 2
    elif brand=='HP':
        return 3
    elif brand=='DELL':
        return 4
    elif brand=='RedmiBook':
        return 5
    elif brand=='realme':
        return 6
    elif brand=='acer':
        return 7
    elif brand=='MSI':
        return 8
    elif brand=='APPLE':
        return 9
    elif brand=='Infinix':
        return 10
    elif brand=='SAMSUNG':
        return 11
    elif brand=='Ultimus':
        return 12
    elif brand=='Vaio':
        return 13
    elif brand=='GIGABYTE':
        return 14
    elif brand=='Nokia':
        return 15
    elif brand=='ALIENWARE':
        return 16
    
data['Brand']=data['Brand'].apply(replace_brand)
data['Brand'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int64)

#### PROCESSOR TYPE

In [6]:
data['Processor Type'].unique()

array(['Intel Core i3', 'AMD Ryzen 5 Hexa Core', 'Intel Core i5',
       'Intel i3-1115G4', 'AMD Ryzen 7 Quad Core',
       'AMD Ryzen 5 Quad Core', 'AMD Ryzen 9 Octa Core',
       'AMD Ryzen 7 Octa Core', 'Apple M1', 'Intel Celeron Dual Core',
       'AMD Ryzen 3 Dual Core', 'AMD Athlon Dual Core',
       'Intel Evo Core i5', 'AMD Ryzen 3 Quad Core', 'Apple M2',
       'AMD Ryzen R5-5600H', 'Intel Celeron Quad Core', 'Intel Core i7',
       'Apple M1 Pro', 'Qualcomm Snapdragon 7c Gen 2', 'Intel PQC-N5030',
       'Gen Intel Evo Core i5', 'Apple M1 Max', 'Intel Core i9',
       'Intel Pentium Silver', 'Intel i3-1125G4', 'AMD Ryzen 5-3450U',
       'AMD Ryzen 5 Dual Core', 'Intel Core i5-1135G7',
       'Intel Core i3-1005G1', 'Intel Pentium Quad Core',
       'Intel Core i5 Pro', 'AMD Dual Core', 'Intel i7-11800H',
       'AMD Ryzen 3 Hexa Core'], dtype=object)

In [7]:
data['Processor Type'].nunique()

35

**Ther are 35 categories in Processor type, for better Model performance its better to drop this column.**

In [8]:
data.drop('Processor Type', axis=1, inplace=True)

#### OPERATING SYSTEM

In [9]:
data['Operating System'].unique()

array(['Windows 11', 'Windows 10', 'Mac', 'Chrome', 'DOS'], dtype=object)

In [10]:
def replace_os(os):
    if os=='Windows 11':
        return 1
    elif os=='Windows 10':
        return 2
    elif os=='Mac':
        return 3
    elif os=='Chrome':
        return 4
    elif os=='DOS':
        return 5
    
data['Operating System']=data['Operating System'].apply(replace_os)
data['Operating System'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

#### RAM TYPE

In [11]:
data['RAM Type'].unique()

array(['DDR4', 'DDR5', 'LPDDR4', 'Unified', 'LPDDR4X', 'LPDDR5', 'LPDDR3'],
      dtype=object)

In [12]:
def replace_ram_type(ram_type):
    if ram_type=='DDR4':
        return 1
    elif ram_type=='DDR5':
        return 2
    elif ram_type=='LPDDR4':
        return 3
    elif ram_type=='Unified':
        return 4
    elif ram_type=='LPDDR4X':
        return 5
    elif ram_type=='LPDDR5':
        return 6
    elif ram_type=='LPDDR3':
        return 7
    
data['RAM Type']=data['RAM Type'].apply(replace_ram_type)
data['RAM Type'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

#### RAM SIZE

In [13]:
data['RAM Size'].unique()

array(['8GB', '16GB', '4GB', '32GB'], dtype=object)

In [14]:
def replace_ram_size(ram_size):
    if ram_size=='8GB':
        return 1
    elif ram_size=='16GB':
        return 2
    elif ram_size=='4GB':
        return 3
    elif ram_size=='32GB':
        return 4

    
data['RAM Size']=data['RAM Size'].apply(replace_ram_size)
data['RAM Size'].unique()

array([1, 2, 3, 4], dtype=int64)

#### DISC TYPE

In [15]:
data['Disc Type'].unique()

array(['SSD', 'HDD', 'EMMC'], dtype=object)

In [16]:
def replace_disc_type(disc_type):
    if disc_type=='SSD':
        return 1
    elif disc_type=='HDD':
        return 2
    elif disc_type=='EMMC':
        return 3

    
data['Disc Type']=data['Disc Type'].apply(replace_disc_type)
data['Disc Type'].unique()

array([1, 2, 3], dtype=int64)

#### DISC SIZE

In [17]:
data['Disc Size'].unique()

array(['256GB', '512GB', '1TB', '128GB', '64GB', '32GB', '2TB'],
      dtype=object)

In [18]:
def replace_disc_size(disc_size):
    if disc_size=='256GB':
        return 1
    elif disc_size=='512GB':
        return 2
    elif disc_size=='1TB':
        return 3
    elif disc_size=='128GB':
        return 4
    elif disc_size=='64GB':
        return 5
    elif disc_size=='32GB':
        return 6
    elif disc_size=='2TB':
        return 7
    
data['Disc Size']=data['Disc Size'].apply(replace_disc_size)
data['Disc Size'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [19]:
data.head()

Brand  Operating System  RAM Type  RAM Size  Disc Type  Disc Size    MRP
0      1                 1         1         1          1          1  36990
1      1                 1         1         1          1          2  39990
2      2                 1         1         1          1          2  32990
3      3                 2         1         1          1          2  49990
4      2                 1         1         1          1          2  49990

### Split into dependent and independent

In [83]:
X=data.drop('MRP', axis=1).values
y=data['MRP'].values

In [84]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
std=StandardScaler()
X=std.fit_transform(X)

print(X)

[[-0.80688224 -0.46911664 -0.42107258 -0.76754824 -0.28058001 -1.45873792]
 [-0.80688224 -0.46911664 -0.42107258 -0.76754824 -0.28058001 -0.31711694]
 [-0.44104142 -0.46911664 -0.42107258 -0.76754824 -0.28058001 -0.31711694]
 ...
 [-0.44104142 -0.46911664  0.46281156  0.65676808 -0.28058001  0.82450404]
 [-0.44104142 -0.46911664  3.99834813  0.65676808 -0.28058001 -0.31711694]
 [-0.80688224  1.21970327 -0.42107258 -0.76754824  2.69026717  0.82450404]]


### Split into training and testing set

In [85]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(576, 6)
(576,)
(144, 6)
(144,)


### Machine Learning Regression Models

### 1. Linear Regression

In [86]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr=lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [87]:
from sklearn.metrics import mean_squared_error as mse, r2_score

MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

results=pd.DataFrame({"Model":["Linear Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
results

Model           MSE      RMSE  R2 Score
0  Linear Regression  1.124345e+09  33531.25  0.529182

### 2. Decision Tree

In [88]:
from sklearn.tree import DecisionTreeRegressor

dt=DecisionTreeRegressor(random_state=0)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [89]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Decision Tree Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0         Linear Regression  1.124345e+09  33531.25  0.529182
0  Decision Tree Regression  7.624300e+08  27612.13  0.797777

### 3. Random Forest

In [90]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor(n_estimators=100)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [91]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Random Forest Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0         Linear Regression  1.124345e+09  33531.25  0.529182
0  Decision Tree Regression  7.624300e+08  27612.13  0.797777
0  Random Forest Regression  6.073773e+08  24645.03  0.824488

### 4. Gradient boosting

In [92]:
from sklearn.ensemble import GradientBoostingRegressor

grb= GradientBoostingRegressor(n_estimators =100,random_state =0) 
grb.fit(x_train, y_train) 
y_pred = grb.predict(x_test)

In [93]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Gradient Boosting Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.124345e+09  33531.25  0.529182
0      Decision Tree Regression  7.624300e+08  27612.13  0.797777
0      Random Forest Regression  6.073773e+08  24645.03  0.824488
0  Gradient Boosting Regression  6.055221e+08  24607.36  0.843721

### 5. ADA Boost

In [94]:
from sklearn.ensemble import AdaBoostRegressor

ada=AdaBoostRegressor(n_estimators=100,learning_rate=0.001,random_state=0)
ada.fit(x_train,y_train)
y_pred=ada.predict(x_test)

In [95]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["ADA Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.124345e+09  33531.25  0.529182
0      Decision Tree Regression  7.624300e+08  27612.13  0.797777
0      Random Forest Regression  6.073773e+08  24645.03  0.824488
0  Gradient Boosting Regression  6.055221e+08  24607.36  0.843721
0          ADA Boost Regression  7.620817e+08  27605.83  0.741301

### XG boost

In [96]:
from xgboost import XGBRegressor

xgb=XGBRegressor(verbosity=0) 
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

In [97]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["XG Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.124345e+09  33531.25  0.529182
0      Decision Tree Regression  7.624300e+08  27612.13  0.797777
0      Random Forest Regression  6.073773e+08  24645.03  0.824488
0  Gradient Boosting Regression  6.055221e+08  24607.36  0.843721
0          ADA Boost Regression  7.620817e+08  27605.83  0.741301
0           XG Boost Regression  5.647867e+08  23765.24  0.842765

### XG boost regressor has high R2 score and low RMSE, tune this model and select this to predict the price of Laptop.

In [130]:
xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

print(mse(y_pred,y_test).round(2))
print(np.sqrt(mse(y_pred,y_test).round(2)))
print(((r2_score(y_pred, y_test))*100).round(2),'%')

507873041.81
22536.038733770405
85.54 %


### Cross validation to check model performace

In [149]:
from sklearn.model_selection import cross_val_score, KFold, ShuffleSplit

xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

k=ShuffleSplit(n_splits=20, test_size=0.2, random_state=20)
score=cross_val_score(xgb, X,y, cv=k)
print("Cross validations Score:\n", score)
print("Average Cross validations Score:", score.mean())
print("Maximum Cross validations Score:", score.max())
print("Minimum Cross validations Score:", score.min())

Cross validations Score:
 [0.85327254 0.8072448  0.88739246 0.88826215 0.85631798 0.89183563
 0.75789464 0.84328718 0.82383686 0.80722334 0.76111133 0.8568727
 0.88182953 0.82769187 0.80653717 0.86349844 0.83342778 0.87671139
 0.86459773 0.85135198]
Average Cross validations Score: 0.8420098752789336
Maximum Cross validations Score: 0.8918356271420067
Minimum Cross validations Score: 0.757894639360678


### Applying cross validation not improving model performance.

### Save model as pickle object

In [150]:
import pickle
pickle.dump(xgb, open('laptop_price_prediction_model.pkl', 'wb'))