### Import Library

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Load data

In [37]:
data=pd.read_csv('D:\\DATA SCIENCE Internship with Innomatics\\laptop_price_prediction\\resourses\\data\\laptop_price.csv')
data.head()

Brand Operating System Processor RAM Type RAM Size Disc Type Disc Size  \
0  Lenovo       Windows 11     Intel     DDR4      8GB       SSD     256GB   
1  Lenovo       Windows 11     Intel     DDR4      8GB       SSD     512GB   
2    ASUS       Windows 11     Intel     DDR4      8GB       SSD     512GB   
3      HP       Windows 10       AMD     DDR4      8GB       SSD     512GB   
4    ASUS       Windows 11     Intel     DDR4      8GB       SSD     512GB   

     MRP  
0  36990  
1  39990  
2  32990  
3  49990  
4  49990

### Create Input and output features

In [38]:
X=data.drop('MRP', axis=1)
y=data['MRP']

### Create Dummies using one hot encoding

In [39]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder()
ohe_fit=ohe.fit(X)
X=ohe_fit.transform(X).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Standardize the features

In [40]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
std_fit=std.fit(X)
X=std_fit.transform(X)
print(X)

[[-0.06468462 -0.16463334 -0.73156082 ... -0.03729371 -1.04257207
  -0.09908417]
 [-0.06468462 -0.16463334 -0.73156082 ... -0.03729371  0.9591663
  -0.09908417]
 [-0.06468462 -0.16463334  1.36694034 ... -0.03729371  0.9591663
  -0.09908417]
 ...
 [-0.06468462 -0.16463334  1.36694034 ... -0.03729371 -1.04257207
  -0.09908417]
 [-0.06468462 -0.16463334  1.36694034 ... -0.03729371  0.9591663
  -0.09908417]
 [-0.06468462 -0.16463334 -0.73156082 ... -0.03729371 -1.04257207
  -0.09908417]]


### SPlit data into train test

In [41]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(576, 46)
(576,)
(144, 46)
(144,)


### Training and evaluating the model

In [42]:
from sklearn.metrics import mean_squared_error as mse, r2_score
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
r2_score(y_pred, y_test).round(2)

0.83

### Test the model for New Data

In [35]:
#Take required input from user
brand=input("Enter Brand here:")
os=input("Enter OS here:")
processor=input("Enter Processor here:")
ram_type=input("Enter RAM Type here:")
ram_size=input("Enter RAM Size here:")
disc_type=input("Enter Disc Type here:")
disc_size=input("Enter Disc Size here:")

#Create dataframe
sample=pd.DataFrame({'Brand':[brand], 'Operating System':[os], 'Processor':[processor],
                   'RAM Type':[ram_type], 'RAM Size':[ram_size],
                   'Disc Type':[disc_type], 'Disc Size':[disc_size]})
sample

Enter Brand here:Lenovo
Enter OS here:Windows 11
Enter Processor here:Intel
Enter RAM Type here:DDR4
Enter RAM Size here:32GB
Enter Disc Type here:SSD
Enter Disc Size here:1TB


Brand Operating System Processor RAM Type RAM Size Disc Type Disc Size
0  Lenovo       Windows 11     Intel     DDR4     32GB       SSD       1TB

#### we have created One Hot Encoding object previosly so use that object to transform the data

In [36]:
sample1=ohe_fit.transform(sample).toarray()
sample1

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.]])

#### we have created Standard Scaler object previously so use that object to transform the data

In [43]:
sample2=std_fit.transform(sample1)
sample2

array([[-0.06468462, -0.16463334, -0.73156082, -0.30424413, -0.03729371,
        -0.30424413, -0.16903085,  1.63507473, -0.20851441, -0.03729371,
        -0.21211493, -0.05277798, -0.05277798, -0.03729371, -0.22604179,
        -0.09166985, -0.09908417, -0.05277798, -0.17332893, -0.46719815,
         0.53237436, -0.86953871, -0.16463334,  0.91986621, -0.03729371,
         0.53237436, -0.38274902, -0.03729371, -0.10599979, -0.23275044,
        -0.11250879, -0.13018891, -0.75861212,  6.43062526, -0.23275044,
        -1.12751646, -0.11867817, -0.26726124,  0.29599543, -0.10599979,
         1.49288297, -0.3992747 , -0.09908417, -0.03729371, -1.04257207,
        -0.09908417]])

### Predict the laptop price

#### use already trained random forest model

In [44]:
rf.predict(sample2)

array([338605.58])