### Import Library

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Load data

In [20]:
data=pd.read_csv('D:\\DATA SCIENCE Internship with Innomatics\\laptop_price_prediction\\resourses\\data\\laptop_price.csv')
data.head()

Brand Operating System Processor RAM Type RAM Size Disc Type Disc Size  \
0  Lenovo       Windows 11     Intel     DDR4      8GB       SSD     256GB   
1  Lenovo       Windows 11     Intel     DDR4      8GB       SSD     512GB   
2    ASUS       Windows 11     Intel     DDR4      8GB       SSD     512GB   
3      HP       Windows 10       AMD     DDR4      8GB       SSD     512GB   
4    ASUS       Windows 11     Intel     DDR4      8GB       SSD     512GB   

     MRP  
0  36990  
1  39990  
2  32990  
3  49990  
4  49990

### Create Input and output features

In [21]:
X=data.drop('MRP', axis=1)
y=data['MRP']

### Split into train and test

In [22]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(576, 7)
(576,)
(144, 7)
(144,)


### Create Dummies using one hot encoding

In [23]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder()
ohe_fit=ohe.fit(x_train)
x_train_tf=ohe_fit.transform(x_train).toarray()
x_train_tf

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [24]:
x_test_tf=ohe_fit.transform(x_test).toarray()
x_test_tf

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Training and evaluating the model

In [25]:
from sklearn.metrics import mean_squared_error as mse, r2_score
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor()
rf.fit(x_train_tf,y_train)
y_pred=rf.predict(x_test_tf)
r2_score(y_pred, y_test).round(2)

0.89

### Test the model for New Data

In [26]:
#Take required input from user
brand=input("Enter Brand here:")
os=input("Enter OS here:")
processor=input("Enter Processor here:")
ram_type=input("Enter RAM Type here:")
ram_size=input("Enter RAM Size here:")
disc_type=input("Enter Disc Type here:")
disc_size=input("Enter Disc Size here:")

#Create dataframe
sample=pd.DataFrame({'Brand':[brand], 'Operating System':[os], 'Processor':[processor],
                   'RAM Type':[ram_type], 'RAM Size':[ram_size],
                   'Disc Type':[disc_type], 'Disc Size':[disc_size]})
sample

Enter Brand here:Lenovo
Enter OS here:Windows 11
Enter Processor here:Intel
Enter RAM Type here:DDR4
Enter RAM Size here:16GB
Enter Disc Type here:HDD
Enter Disc Size here:256GB


Brand Operating System Processor RAM Type RAM Size Disc Type Disc Size
0  Lenovo       Windows 11     Intel     DDR4     16GB       HDD     256GB

#### we have created One Hot Encoding object previosly so use that object to transform the data

In [27]:
sample1=ohe_fit.transform(sample).toarray()
sample1

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.]])

### Predict the laptop price

#### use already trained random forest model

In [29]:
rf.predict(sample1)

array([115446.01190476])